/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse53.stm.view;

import cambodia.raven.DateChooser;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.gdse53.stm.controller.ExamFormController;

/**
 *
 * @author Yashitha Nadiranga
 */
public class ExamShedule extends javax.swing.JFrame {

    /**
     * Creates new form ExamShedule
     */
    int mouseX;
    int mouseY;

    public ExamShedule() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        genesid();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new cambodia.raven.DateChooser();
        txteid = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        lblexit = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btncal = new keeptoo.KButton();
        txtdate = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnsubmit = new keeptoo.KButton();
        jLabel16 = new javax.swing.JLabel();
        txtename = new javax.swing.JTextField();
        lblminimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        dateChooser1.setButton(btncal);
        dateChooser1.setTextRefernce(txtdate);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txteid.setEditable(false);
        txteid.setBackground(new java.awt.Color(53, 63, 89));
        txteid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txteid.setForeground(new java.awt.Color(255, 255, 255));
        txteid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txteid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteidActionPerformed(evt);
            }
        });
        getContentPane().add(txteid, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 460, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Exam Date     :");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 130, -1));

        lblexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_close_window_30px.png"))); // NOI18N
        lblexit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblexitMouseClicked(evt);
            }
        });
        getContentPane().add(lblexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 0, -1, 59));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Exam Name    :");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 232, 130, 30));

        btncal.setText("Select");
        btncal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btncal.setkAllowGradient(false);
        btncal.setkBackGroundColor(new java.awt.Color(11, 182, 83));
        btncal.setkHoverColor(new java.awt.Color(9, 135, 62));
        btncal.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        getContentPane().add(btncal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 80, 30));

        txtdate.setBackground(new java.awt.Color(53, 63, 89));
        txtdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtdate.setForeground(new java.awt.Color(255, 255, 255));
        txtdate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 360, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Exam ID        :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 130, -1));

        btnsubmit.setText("Submit");
        btnsubmit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnsubmit.setkAllowGradient(false);
        btnsubmit.setkBackGroundColor(new java.awt.Color(11, 182, 83));
        btnsubmit.setkHoverColor(new java.awt.Color(9, 135, 62));
        btnsubmit.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 230, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Add Exam Schedule");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        txtename.setBackground(new java.awt.Color(53, 63, 89));
        txtename.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtename.setForeground(new java.awt.Color(255, 255, 255));
        txtename.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        getContentPane().add(txtename, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 460, 30));

        lblminimize.setForeground(new java.awt.Color(255, 255, 255));
        lblminimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_minus_20px.png"))); // NOI18N
        lblminimize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblminimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblminimizeMouseClicked(evt);
            }
        });
        getContentPane().add(lblminimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(827, 0, -1, 59));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/examback.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        uploadexamShedule();
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void lblexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblexitMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblexitMouseClicked

    private void lblminimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizeMouseClicked
        this.setState(MainForm.ICONIFIED);
    }//GEN-LAST:event_lblminimizeMouseClicked

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void txteidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txteidActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int X = evt.getXOnScreen();
        int Y = evt.getYOnScreen();

        this.setLocation(X - mouseX, Y - mouseY);
    }//GEN-LAST:event_jLabel1MouseDragged

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ExamShedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new ExamShedule().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btncal;
    private keeptoo.KButton btnsubmit;
    private cambodia.raven.DateChooser dateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel lblexit;
    private javax.swing.JLabel lblminimize;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txteid;
    private javax.swing.JTextField txtename;
    // End of variables declaration//GEN-END:variables

    private void uploadexamShedule() {
        if (checkValidationExamShedule()) {
            try {
                String date = dateChooser1.getSelectedDate(DateChooser.GET_YEAR) + "-"
                        + dateChooser1.getSelectedDate(DateChooser.GET_MONTH)
                        + "-" + dateChooser1.getSelectedDate(DateChooser.GET_DAY);

                lk.ijse.gdse53.stm.model.ExamShedule e1 = new lk.ijse.gdse53.stm.model.ExamShedule(
                        txteid.getText(),
                        txtename.getText(),
                        date
                );

                if (new ExamFormController().uploadExamShedule(e1)) {
                    JOptionPane.showMessageDialog(null, "Exam added successfuly!");
                    genesid();
                } else {
                    JOptionPane.showMessageDialog(null, "Oops! something went wrong");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(ExamShedule.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private boolean checkValidationExamShedule() {
        if (!"".equals(txteid.getText())) {
            if (!"".equals(txtename.getText())) {
                return true;
            } else {
                JOptionPane.showMessageDialog(null, "Please Add Exam Name");
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please Add Exam ESID");
            return false;
        }
    }

    private void genesid() {
        try {
            String esid = new ExamFormController().getEsid();
            esid = esid.replaceAll("ES", "");
            int id = Integer.parseInt(esid);
            id = ++id;
            if (id < 10) {
                txteid.setText(String.valueOf("ES00" + id));

            } else if (id < 100) {
                txteid.setText(String.valueOf("ES0" + id));
            } else {
                txteid.setText(String.valueOf("ES" + id));
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ExamShedule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
