/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse53.stm.view;

import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.ijse.gdse53.stm.controller.HomeFormController;

/**
 *
 * @author Yashitha Nadiranga
 */
public class HomeForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddStudentForm
     */
    static String value;

    public HomeForm() {
        initComponents();
        setBorder();
        dateTime();
        loadAllStudent();
        setAttendanceCount();
        loadExamCount();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        lblTotalStudent = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        lblexamcount = new javax.swing.JLabel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        lblattcount = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        dateChooser1 = new cambodia.raven.DateChooser();
        jLabel11 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kGradientPanel16 = new keeptoo.KGradientPanel();
        kGradientPanel17 = new keeptoo.KGradientPanel();
        kButton4 = new keeptoo.KButton();
        kButton6 = new keeptoo.KButton();
        jLabel16 = new javax.swing.JLabel();
        kGradientPanel9 = new keeptoo.KGradientPanel();
        kButton5 = new keeptoo.KButton();
        jLabel7 = new javax.swing.JLabel();
        kGradientPanel18 = new keeptoo.KGradientPanel();
        kGradientPanel19 = new keeptoo.KGradientPanel();
        kButton7 = new keeptoo.KButton();
        kButton8 = new keeptoo.KButton();
        jLabel8 = new javax.swing.JLabel();
        kGradientPanel20 = new keeptoo.KGradientPanel();
        kGradientPanel21 = new keeptoo.KGradientPanel();
        kButton9 = new keeptoo.KButton();
        kButton10 = new keeptoo.KButton();
        jLabel9 = new javax.swing.JLabel();
        kGradientPanel22 = new keeptoo.KGradientPanel();
        kGradientPanel23 = new keeptoo.KGradientPanel();
        kButton11 = new keeptoo.KButton();
        kButton12 = new keeptoo.KButton();
        jLabel14 = new javax.swing.JLabel();
        kGradientPanel24 = new keeptoo.KGradientPanel();
        kGradientPanel25 = new keeptoo.KGradientPanel();
        kButton13 = new keeptoo.KButton();
        kButton14 = new keeptoo.KButton();
        jLabel15 = new javax.swing.JLabel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(53, 63, 89));
        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setFrameIcon(null);

        jPanel1.setBackground(new java.awt.Color(53, 63, 89));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setBackground(new java.awt.Color(53, 63, 89));
        kGradientPanel1.setkBorderRadius(20);
        kGradientPanel1.setkEndColor(new java.awt.Color(11, 182, 83));
        kGradientPanel1.setkStartColor(new java.awt.Color(11, 182, 83));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Student");

        lblTotalStudent.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        lblTotalStudent.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalStudent.setText("0");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblTotalStudent)))
                .addGap(72, 72, 72))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lblTotalStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 270, 91));

        kGradientPanel3.setBackground(new java.awt.Color(53, 63, 89));
        kGradientPanel3.setkBorderRadius(20);
        kGradientPanel3.setkEndColor(new java.awt.Color(11, 182, 83));
        kGradientPanel3.setkStartColor(new java.awt.Color(11, 182, 83));

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Today Exams");

        lblexamcount.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        lblexamcount.setForeground(new java.awt.Color(255, 255, 255));
        lblexamcount.setText("0");

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblexamcount)))
                .addGap(87, 87, 87))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lblexamcount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel1.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 300, 91));

        kGradientPanel4.setBackground(new java.awt.Color(53, 63, 89));
        kGradientPanel4.setkBorderRadius(20);
        kGradientPanel4.setkEndColor(new java.awt.Color(11, 182, 83));
        kGradientPanel4.setkStartColor(new java.awt.Color(11, 182, 83));

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Today Attendance");

        lblattcount.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        lblattcount.setForeground(new java.awt.Color(255, 255, 255));
        lblattcount.setText("0");

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel4Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lblattcount))
                    .addComponent(jLabel5))
                .addGap(46, 46, 46))
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lblattcount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel1.add(kGradientPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 150, 280, 91));

        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Dashboard");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        lbltime.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbltime.setForeground(new java.awt.Color(255, 255, 255));
        lbltime.setText("00:00");
        jPanel1.add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, -1, -1));
        jPanel1.add(dateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 290, -1, 230));

        jLabel11.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("HORANA");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 690, -1, -1));

        kGradientPanel2.setkEndColor(new java.awt.Color(204, 204, 204));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_menu_vertical_30px.png"))); // NOI18N
        kGradientPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 13, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_available_updates_30px.png"))); // NOI18N
        kGradientPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel6.setText("News & Events");
        kGradientPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 15, -1, -1));

        kGradientPanel16.setkEndColor(new java.awt.Color(250, 250, 250));
        kGradientPanel16.setkStartColor(new java.awt.Color(250, 250, 250));
        kGradientPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel17.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel17.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton4.setText("News");
        kButton4.setkAllowGradient(false);
        kButton4.setkBackGroundColor(new java.awt.Color(255, 51, 51));
        kGradientPanel17.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        kGradientPanel16.add(kGradientPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 748, 50));

        kButton6.setText("News");
        kButton6.setkAllowGradient(false);
        kButton6.setkBackGroundColor(new java.awt.Color(51, 102, 255));
        kButton6.setkHoverColor(new java.awt.Color(0, 0, 153));
        kButton6.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton6.setkPressedColor(new java.awt.Color(102, 51, 255));
        kGradientPanel16.add(kButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("No News & Events Available");
        kGradientPanel16.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        kGradientPanel2.add(kGradientPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 748, 50));

        kGradientPanel9.setkEndColor(new java.awt.Color(250, 250, 250));
        kGradientPanel9.setkStartColor(new java.awt.Color(250, 250, 250));
        kGradientPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton5.setText("News");
        kButton5.setkAllowGradient(false);
        kButton5.setkBackGroundColor(new java.awt.Color(51, 102, 255));
        kButton5.setkHoverColor(new java.awt.Color(0, 0, 153));
        kButton5.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton5.setkPressedColor(new java.awt.Color(102, 51, 255));
        kGradientPanel9.add(kButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("No News & Events Available");
        kGradientPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        kGradientPanel2.add(kGradientPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 748, 50));

        kGradientPanel18.setkEndColor(new java.awt.Color(250, 250, 250));
        kGradientPanel18.setkStartColor(new java.awt.Color(250, 250, 250));
        kGradientPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel19.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel19.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton7.setText("News");
        kButton7.setkAllowGradient(false);
        kButton7.setkBackGroundColor(new java.awt.Color(255, 51, 51));
        kGradientPanel19.add(kButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        kGradientPanel18.add(kGradientPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 748, 50));

        kButton8.setText("News");
        kButton8.setkAllowGradient(false);
        kButton8.setkBackGroundColor(new java.awt.Color(51, 102, 255));
        kButton8.setkHoverColor(new java.awt.Color(0, 0, 153));
        kButton8.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton8.setkPressedColor(new java.awt.Color(102, 51, 255));
        kGradientPanel18.add(kButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("No News & Events Available");
        kGradientPanel18.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        kGradientPanel2.add(kGradientPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 748, 50));

        kGradientPanel20.setkEndColor(new java.awt.Color(250, 250, 250));
        kGradientPanel20.setkStartColor(new java.awt.Color(250, 250, 250));
        kGradientPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel21.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel21.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton9.setText("News");
        kButton9.setkAllowGradient(false);
        kButton9.setkBackGroundColor(new java.awt.Color(255, 51, 51));
        kGradientPanel21.add(kButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        kGradientPanel20.add(kGradientPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 748, 50));

        kButton10.setText("News");
        kButton10.setkAllowGradient(false);
        kButton10.setkBackGroundColor(new java.awt.Color(51, 102, 255));
        kButton10.setkHoverColor(new java.awt.Color(0, 0, 153));
        kButton10.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton10.setkPressedColor(new java.awt.Color(102, 51, 255));
        kGradientPanel20.add(kButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("No News & Events Available");
        kGradientPanel20.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        kGradientPanel2.add(kGradientPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 748, 50));

        kGradientPanel22.setkEndColor(new java.awt.Color(250, 250, 250));
        kGradientPanel22.setkStartColor(new java.awt.Color(250, 250, 250));
        kGradientPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel23.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel23.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton11.setText("News");
        kButton11.setkAllowGradient(false);
        kButton11.setkBackGroundColor(new java.awt.Color(255, 51, 51));
        kGradientPanel23.add(kButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        kGradientPanel22.add(kGradientPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 748, 50));

        kButton12.setText("News");
        kButton12.setkAllowGradient(false);
        kButton12.setkBackGroundColor(new java.awt.Color(51, 102, 255));
        kButton12.setkHoverColor(new java.awt.Color(0, 0, 153));
        kButton12.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton12.setkPressedColor(new java.awt.Color(102, 51, 255));
        kGradientPanel22.add(kButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("No News & Events Available");
        kGradientPanel22.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        kGradientPanel2.add(kGradientPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 750, 50));

        kGradientPanel24.setkEndColor(new java.awt.Color(250, 250, 250));
        kGradientPanel24.setkStartColor(new java.awt.Color(250, 250, 250));
        kGradientPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel25.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel25.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton13.setText("News");
        kButton13.setkAllowGradient(false);
        kButton13.setkBackGroundColor(new java.awt.Color(255, 51, 51));
        kGradientPanel25.add(kButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        kGradientPanel24.add(kGradientPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 748, 50));

        kButton14.setText("News");
        kButton14.setkAllowGradient(false);
        kButton14.setkBackGroundColor(new java.awt.Color(51, 102, 255));
        kButton14.setkHoverColor(new java.awt.Color(0, 0, 153));
        kButton14.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton14.setkPressedColor(new java.awt.Color(102, 51, 255));
        kGradientPanel24.add(kButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("No News & Events Available");
        kGradientPanel24.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        kGradientPanel2.add(kGradientPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 748, 50));

        jPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 750, 450));

        kGradientPanel5.setBackground(new java.awt.Color(53, 63, 89));

        jLabel12.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("INSTITUTE OF TECHNOLOGY");

        jLabel13.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("UNITY");

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel5Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel5Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        jPanel1.add(kGradientPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 572, 260, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cambodia.raven.DateChooser dateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KButton kButton10;
    private keeptoo.KButton kButton11;
    private keeptoo.KButton kButton12;
    private keeptoo.KButton kButton13;
    private keeptoo.KButton kButton14;
    private keeptoo.KButton kButton4;
    private keeptoo.KButton kButton5;
    private keeptoo.KButton kButton6;
    private keeptoo.KButton kButton7;
    private keeptoo.KButton kButton8;
    private keeptoo.KButton kButton9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel16;
    private keeptoo.KGradientPanel kGradientPanel17;
    private keeptoo.KGradientPanel kGradientPanel18;
    private keeptoo.KGradientPanel kGradientPanel19;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel20;
    private keeptoo.KGradientPanel kGradientPanel21;
    private keeptoo.KGradientPanel kGradientPanel22;
    private keeptoo.KGradientPanel kGradientPanel23;
    private keeptoo.KGradientPanel kGradientPanel24;
    private keeptoo.KGradientPanel kGradientPanel25;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel9;
    private javax.swing.JLabel lblTotalStudent;
    private javax.swing.JLabel lblattcount;
    private javax.swing.JLabel lblexamcount;
    private javax.swing.JLabel lbltime;
    // End of variables declaration//GEN-END:variables

    private void loadAllStudent() {

        try {
            int studentcount = new HomeFormController().getAllStudent();
            lblTotalStudent.setText(String.valueOf(studentcount));
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void dateTime() {
        Timer t = new Timer();
        t.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
                LocalDateTime now = LocalDateTime.now();
                lbltime.setText(now.toLocalDate().toString() + "   " + now.getHour() + ":" + now.getMinute() + ":" + now.getSecond());
            }
        }, 0, 1000);
    }

    private void setBorder() {
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }
    private void setAttendanceCount(){
        try {
            String count = new HomeFormController().getAttendanceCount();
            lblattcount.setText(count);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadExamCount() {
        try {
            String ecount = new HomeFormController().getexamCount();
            lblexamcount.setText(ecount);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
