/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse53.stm.view;

import java.awt.Color;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.gdse53.stm.controller.LoginController;

/**
 *
 * @author Yashitha Nadiranga
 */
public class Login extends javax.swing.JFrame {

    int mouseX;
    int mouseY;

    public Login() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        cbshow.setSelected(true);
        txtpassword.setEchoChar((char) 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbshow = new javax.swing.JCheckBox();
        lbliot = new javax.swing.JLabel();
        lblunity = new javax.swing.JLabel();
        lblbackimage = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        lbllogin = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        backpanal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblclose = new javax.swing.JLabel();
        btnlogin = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 545));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/5ea3017132e9c.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 127, -1, 610));

        cbshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbshowMouseClicked(evt);
            }
        });
        jPanel2.add(cbshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        lbliot.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        lbliot.setForeground(new java.awt.Color(255, 255, 255));
        lbliot.setText("INSTITUTE OF TECHNOLOGY");
        jPanel2.add(lbliot, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 320, -1));

        lblunity.setFont(new java.awt.Font("Poppins SemiBold", 0, 48)); // NOI18N
        lblunity.setForeground(new java.awt.Color(255, 255, 255));
        lblunity.setText("U  N  I  T  Y");
        jPanel2.add(lblunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 260, 70));

        lblbackimage.setFont(new java.awt.Font("Poppins Black", 0, 36)); // NOI18N
        lblbackimage.setForeground(new java.awt.Color(255, 255, 255));
        lblbackimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/login background.png"))); // NOI18N
        jPanel2.add(lblbackimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        txtusername.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        txtusername.setForeground(new java.awt.Color(153, 153, 153));
        txtusername.setText("User Name");
        txtusername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtusernameMouseClicked(evt);
            }
        });
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        jPanel2.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 290, -1));

        lbllogin.setFont(new java.awt.Font("Poppins SemiBold", 1, 36)); // NOI18N
        lbllogin.setForeground(new java.awt.Color(51, 51, 51));
        lbllogin.setText("Sign - In");
        jPanel2.add(lbllogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 180, 50));

        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(153, 153, 153));
        txtpassword.setText("Password");
        txtpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpasswordMouseClicked(evt);
            }
        });
        jPanel2.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 290, -1));

        backpanal.setBackground(new java.awt.Color(255, 255, 255));
        backpanal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backpanalMouseDragged(evt);
            }
        });
        backpanal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backpanalMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backpanalMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_minimize_window_30px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        lblclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_close_window_30px.png"))); // NOI18N
        lblclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcloseMouseClicked(evt);
            }
        });

        btnlogin.setBackground(new java.awt.Color(51, 0, 255));
        btnlogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnlogin.setkBackGroundColor(new java.awt.Color(102, 0, 255));
        btnlogin.setkEndColor(new java.awt.Color(102, 51, 255));
        btnlogin.setkHoverEndColor(new java.awt.Color(0, 0, 153));
        btnlogin.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnlogin.setkHoverStartColor(new java.awt.Color(0, 51, 153));
        btnlogin.setkPressedColor(new java.awt.Color(102, 102, 255));
        btnlogin.setkStartColor(new java.awt.Color(51, 102, 255));
        btnlogin.setLabel("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backpanalLayout = new javax.swing.GroupLayout(backpanal);
        backpanal.setLayout(backpanalLayout);
        backpanalLayout.setHorizontalGroup(
            backpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backpanalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblclose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(551, Short.MAX_VALUE))
        );
        backpanalLayout.setVerticalGroup(
            backpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backpanalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblclose)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 338, Short.MAX_VALUE)
                .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );

        jPanel2.add(backpanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void lblcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblcloseMouseClicked

    private void backpanalMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backpanalMouseDragged
        int X = evt.getXOnScreen();
        int Y = evt.getYOnScreen();

        this.setLocation(X - mouseX, Y - mouseY);
    }//GEN-LAST:event_backpanalMouseDragged

    private void backpanalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backpanalMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_backpanalMousePressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusernameMouseClicked
        if (txtusername.getText().equals("User Name")) {
            txtusername.setText("");
            txtusername.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtusernameMouseClicked

    private void txtpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpasswordMouseClicked
        if (txtpassword.getText().equals("Password")) {
            txtpassword.setText("");
            txtpassword.setForeground(Color.BLACK);
            txtpassword.setEchoChar('*');
            cbshow.setSelected(false);
        }
    }//GEN-LAST:event_txtpasswordMouseClicked

    private void cbshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbshowMouseClicked
        if (cbshow.isSelected()) {
            txtpassword.setEchoChar((char) 0);
        } else {
            txtpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_cbshowMouseClicked

    private void backpanalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backpanalMouseClicked
        if (txtusername.getText().equals("")) {
            txtusername.setText("User Name");
            txtusername.setForeground(Color.gray);
        }

        if (txtpassword.getText().equals("")) {
            txtpassword.setText("Password");
            txtpassword.setForeground(Color.gray);
            txtpassword.setEchoChar((char) 0);
            //cbshow.setSelected(true);
        }
    }//GEN-LAST:event_backpanalMouseClicked

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        if (checkAllField()) {
            try {
                String password = SHA(txtpassword.getText(), "SHA-1");

                try {
                    lk.ijse.gdse53.stm.model.Login l = new lk.ijse.gdse53.stm.model.Login(
                            txtusername.getText(),
                            password
                    );

                    ResultSet rs = new LoginController().checkLogin(l);
                    while (rs.next()) {

                        if (rs.getString(1).equals(txtusername.getText())) {
                            if (rs.getString(2).equals(password)) {
                                new MainForm(rs.getString(3)).setVisible(true);
                                this.dispose();
                                return;
                            } else {
                                JOptionPane.showMessageDialog(null, "Please Check Your Password!");
                                return;
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Please Check Your User Name!");
                            return;
                        }
                    }
                   JOptionPane.showMessageDialog(null, "Please Check Your User Name or Password");
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnloginActionPerformed

    public String SHA(String passwordToHash, String type) throws NoSuchAlgorithmException {
        String generatedPassword = null;

        MessageDigest md = MessageDigest.getInstance(type);
        byte[] bytes = md.digest(passwordToHash.getBytes());
        BigInteger no = new BigInteger(1, bytes);
        String hashtext = no.toString(16);
        while (hashtext.length() < 32) {
            hashtext = "0" + hashtext;
        }
        generatedPassword = hashtext;
        return generatedPassword;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backpanal;
    private keeptoo.KButton btnlogin;
    private javax.swing.JCheckBox cbshow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblbackimage;
    private javax.swing.JLabel lblclose;
    private javax.swing.JLabel lbliot;
    private javax.swing.JLabel lbllogin;
    private javax.swing.JLabel lblunity;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables

    private boolean checkAllField() {
        if (!"".equals(txtusername.getText())) {
            if (!"".equals(txtpassword.getText())) {
                return true;
            } else {
                JOptionPane.showMessageDialog(null, "Please add password !");
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please add user name !");
            return false;
        }
    }

}
