/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse53.stm.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import jssc.SerialPortException;

/**
 *
 * @author Yashitha Nadiranga
 */
public class MainForm extends javax.swing.JFrame {

    int mouseX;
    int mouseY;
    String privilege ;

    MainForm(String string) {
        privilege = string;
        System.out.println(privilege);
        initComponents();
        loadUI();
        setLable();
        pnlmainload.add(new HomeForm()).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlmain = new javax.swing.JPanel();
        pnlhead = new javax.swing.JPanel();
        lblexit = new javax.swing.JLabel();
        lblminimize = new javax.swing.JLabel();
        lblheadlogo = new javax.swing.JLabel();
        lbltitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblpr = new javax.swing.JLabel();
        pnlmainload = new javax.swing.JPanel();
        pnlleft = new javax.swing.JPanel();
        btnhome = new keeptoo.KButton();
        btnaddstudent = new keeptoo.KButton();
        btnviewstudent = new keeptoo.KButton();
        btnattendance = new keeptoo.KButton();
        btnbatch = new keeptoo.KButton();
        btncourse = new keeptoo.KButton();
        btnsubject = new keeptoo.KButton();
        jLabel5 = new javax.swing.JLabel();
        btnexam = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        pnlmain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlhead.setBackground(new java.awt.Color(45, 54, 76));
        pnlhead.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 51, 51)));
        pnlhead.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        pnlhead.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlheadMouseDragged(evt);
            }
        });
        pnlhead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlheadMousePressed(evt);
            }
        });

        lblexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_close_window_30px.png"))); // NOI18N
        lblexit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblexitMouseClicked(evt);
            }
        });

        lblminimize.setForeground(new java.awt.Color(255, 255, 255));
        lblminimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_minus_20px.png"))); // NOI18N
        lblminimize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblminimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblminimizeMouseClicked(evt);
            }
        });

        lblheadlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_student_center_20px.png"))); // NOI18N

        lbltitle.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(255, 255, 255));
        lbltitle.setText("Unity - Institute of Technology");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_administrator_male_30px.png"))); // NOI18N

        lblpr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblpr.setForeground(new java.awt.Color(255, 255, 255));
        lblpr.setText("Admin");

        javax.swing.GroupLayout pnlheadLayout = new javax.swing.GroupLayout(pnlhead);
        pnlhead.setLayout(pnlheadLayout);
        pnlheadLayout.setHorizontalGroup(
            pnlheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlheadLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblheadlogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 881, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblpr)
                .addGap(37, 37, 37)
                .addComponent(lblminimize, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblexit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlheadLayout.setVerticalGroup(
            pnlheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblexit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbltitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblheadlogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblminimize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlheadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblpr, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlmain.add(pnlhead, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 50));

        pnlmainload.setBackground(new java.awt.Color(53, 63, 89));

        javax.swing.GroupLayout pnlmainloadLayout = new javax.swing.GroupLayout(pnlmainload);
        pnlmainload.setLayout(pnlmainloadLayout);
        pnlmainloadLayout.setHorizontalGroup(
            pnlmainloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        pnlmainloadLayout.setVerticalGroup(
            pnlmainloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        pnlmain.add(pnlmainload, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 1110, 780));

        pnlleft.setBackground(new java.awt.Color(45, 54, 76));

        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/home.png"))); // NOI18N
        btnhome.setText("Home");
        btnhome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnhome.setIconTextGap(50);
        btnhome.setkAllowGradient(false);
        btnhome.setkAllowTab(true);
        btnhome.setkBackGroundColor(new java.awt.Color(45, 54, 76));
        btnhome.setkBorderRadius(0);
        btnhome.setkHoverColor(new java.awt.Color(35, 43, 62));
        btnhome.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnhome.setkIndicatorColor(new java.awt.Color(11, 182, 83));
        btnhome.setkIndicatorThickness(6);
        btnhome.setkSelectedColor(new java.awt.Color(101, 52, 172));
        btnhome.setSelected(true);
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        btnaddstudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_add_user_group_man_man_20px.png"))); // NOI18N
        btnaddstudent.setText("Add Student");
        btnaddstudent.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnaddstudent.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnaddstudent.setIconTextGap(50);
        btnaddstudent.setkAllowGradient(false);
        btnaddstudent.setkAllowTab(true);
        btnaddstudent.setkBackGroundColor(new java.awt.Color(45, 54, 76));
        btnaddstudent.setkBorderRadius(0);
        btnaddstudent.setkHoverColor(new java.awt.Color(35, 43, 62));
        btnaddstudent.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnaddstudent.setkIndicatorColor(new java.awt.Color(11, 182, 83));
        btnaddstudent.setkIndicatorThickness(6);
        btnaddstudent.setkSelectedColor(new java.awt.Color(101, 52, 172));
        btnaddstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddstudentActionPerformed(evt);
            }
        });

        btnviewstudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_member_20px.png"))); // NOI18N
        btnviewstudent.setText("View Student");
        btnviewstudent.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnviewstudent.setIconTextGap(50);
        btnviewstudent.setkAllowGradient(false);
        btnviewstudent.setkAllowTab(true);
        btnviewstudent.setkBackGroundColor(new java.awt.Color(45, 54, 76));
        btnviewstudent.setkBorderRadius(0);
        btnviewstudent.setkHoverColor(new java.awt.Color(35, 43, 62));
        btnviewstudent.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnviewstudent.setkIndicatorColor(new java.awt.Color(11, 182, 83));
        btnviewstudent.setkIndicatorThickness(6);
        btnviewstudent.setkSelectedColor(new java.awt.Color(101, 52, 172));
        btnviewstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewstudentActionPerformed(evt);
            }
        });

        btnattendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_attendance_20px.png"))); // NOI18N
        btnattendance.setText("Attendence");
        btnattendance.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnattendance.setIconTextGap(50);
        btnattendance.setkAllowGradient(false);
        btnattendance.setkAllowTab(true);
        btnattendance.setkBackGroundColor(new java.awt.Color(45, 54, 76));
        btnattendance.setkBorderRadius(0);
        btnattendance.setkHoverColor(new java.awt.Color(35, 43, 62));
        btnattendance.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnattendance.setkIndicatorColor(new java.awt.Color(11, 182, 83));
        btnattendance.setkIndicatorThickness(6);
        btnattendance.setkSelectedColor(new java.awt.Color(101, 52, 172));
        btnattendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnattendanceActionPerformed(evt);
            }
        });

        btnbatch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_batch_assign_20px.png"))); // NOI18N
        btnbatch.setText("Batch");
        btnbatch.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnbatch.setIconTextGap(50);
        btnbatch.setkAllowGradient(false);
        btnbatch.setkAllowTab(true);
        btnbatch.setkBackGroundColor(new java.awt.Color(45, 54, 76));
        btnbatch.setkBorderRadius(0);
        btnbatch.setkHoverColor(new java.awt.Color(35, 43, 62));
        btnbatch.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnbatch.setkIndicatorColor(new java.awt.Color(11, 182, 83));
        btnbatch.setkIndicatorThickness(6);
        btnbatch.setkSelectedColor(new java.awt.Color(101, 52, 172));
        btnbatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatchActionPerformed(evt);
            }
        });

        btncourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_diploma_20px.png"))); // NOI18N
        btncourse.setText("Course");
        btncourse.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btncourse.setIconTextGap(50);
        btncourse.setkAllowGradient(false);
        btncourse.setkAllowTab(true);
        btncourse.setkBackGroundColor(new java.awt.Color(45, 54, 76));
        btncourse.setkBorderRadius(0);
        btncourse.setkHoverColor(new java.awt.Color(35, 43, 62));
        btncourse.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btncourse.setkIndicatorColor(new java.awt.Color(11, 182, 83));
        btncourse.setkIndicatorThickness(6);
        btncourse.setkSelectedColor(new java.awt.Color(101, 52, 172));
        btncourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncourseActionPerformed(evt);
            }
        });

        btnsubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_physics_book_20px.png"))); // NOI18N
        btnsubject.setText("Subject");
        btnsubject.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnsubject.setIconTextGap(50);
        btnsubject.setkAllowGradient(false);
        btnsubject.setkAllowTab(true);
        btnsubject.setkBackGroundColor(new java.awt.Color(45, 54, 76));
        btnsubject.setkBorderRadius(0);
        btnsubject.setkHoverColor(new java.awt.Color(35, 43, 62));
        btnsubject.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnsubject.setkIndicatorColor(new java.awt.Color(11, 182, 83));
        btnsubject.setkIndicatorThickness(6);
        btnsubject.setkSelectedColor(new java.awt.Color(101, 52, 172));
        btnsubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubjectActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_attach_resume_male_90px.png"))); // NOI18N

        btnexam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_physics_book_20px.png"))); // NOI18N
        btnexam.setText("Exam");
        btnexam.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnexam.setIconTextGap(50);
        btnexam.setkAllowGradient(false);
        btnexam.setkAllowTab(true);
        btnexam.setkBackGroundColor(new java.awt.Color(45, 54, 76));
        btnexam.setkBorderRadius(0);
        btnexam.setkHoverColor(new java.awt.Color(35, 43, 62));
        btnexam.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnexam.setkIndicatorColor(new java.awt.Color(11, 182, 83));
        btnexam.setkIndicatorThickness(6);
        btnexam.setkSelectedColor(new java.awt.Color(101, 52, 172));
        btnexam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlleftLayout = new javax.swing.GroupLayout(pnlleft);
        pnlleft.setLayout(pnlleftLayout);
        pnlleftLayout.setHorizontalGroup(
            pnlleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnhome, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(btnaddstudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnviewstudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnattendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnbatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btncourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnsubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnexam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlleftLayout.setVerticalGroup(
            pnlleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlleftLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnaddstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnviewstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnattendance, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbatch, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncourse, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsubject, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnexam, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pnlmain.add(pnlleft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 830));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblexitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblexitMouseClicked

    private void lblminimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizeMouseClicked
        this.setState(MainForm.ICONIFIED);
    }//GEN-LAST:event_lblminimizeMouseClicked

    private void pnlheadMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlheadMouseDragged
        int X = evt.getXOnScreen();
        int Y = evt.getYOnScreen();

        this.setLocation(X - mouseX, Y - mouseY);
    }//GEN-LAST:event_pnlheadMouseDragged

    private void pnlheadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlheadMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_pnlheadMousePressed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed

        pnlmainload.removeAll();
        pnlmainload.repaint();
        pnlmainload.add(new HomeForm()).setVisible(true);

    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnaddstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddstudentActionPerformed
        pnlmainload.removeAll();
        pnlmainload.repaint();
        pnlmainload.add(new AddStudentForm()).setVisible(true);
    }//GEN-LAST:event_btnaddstudentActionPerformed

    private void btnviewstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewstudentActionPerformed
        pnlmainload.removeAll();
        pnlmainload.repaint();
        pnlmainload.add(new ViewStudentForm(privilege)).setVisible(true);
    }//GEN-LAST:event_btnviewstudentActionPerformed

    private void btnattendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnattendanceActionPerformed
        pnlmainload.removeAll();
        pnlmainload.repaint();
        try {
            pnlmainload.add(new AttendanceForm()).setVisible(true);
        } catch (SerialPortException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnattendanceActionPerformed

    private void btnbatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatchActionPerformed
        pnlmainload.removeAll();
        pnlmainload.repaint();
        pnlmainload.add(new BatchForm(privilege)).setVisible(true);

    }//GEN-LAST:event_btnbatchActionPerformed

    private void btncourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncourseActionPerformed
        pnlmainload.removeAll();
        pnlmainload.repaint();
        pnlmainload.add(new CourseForm(privilege)).setVisible(true);
    }//GEN-LAST:event_btncourseActionPerformed

    private void btnsubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubjectActionPerformed
        pnlmainload.removeAll();
        pnlmainload.repaint();
        pnlmainload.add(new SubjectForm(privilege)).setVisible(true);
    }//GEN-LAST:event_btnsubjectActionPerformed

    private void btnexamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexamActionPerformed
        try {
            pnlmainload.removeAll();
            pnlmainload.repaint();
            pnlmainload.add(new ExamForm()).setVisible(true);
        } catch (SerialPortException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnexamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnaddstudent;
    private keeptoo.KButton btnattendance;
    private keeptoo.KButton btnbatch;
    private keeptoo.KButton btncourse;
    private keeptoo.KButton btnexam;
    private keeptoo.KButton btnhome;
    private keeptoo.KButton btnsubject;
    private keeptoo.KButton btnviewstudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblexit;
    private javax.swing.JLabel lblheadlogo;
    private javax.swing.JLabel lblminimize;
    private javax.swing.JLabel lblpr;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JPanel pnlhead;
    private javax.swing.JPanel pnlleft;
    private javax.swing.JPanel pnlmain;
    private javax.swing.JPanel pnlmainload;
    // End of variables declaration//GEN-END:variables

    private void loadUI() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    private void setLable() {
       try{
         lblpr.setText(privilege);
       }catch(NullPointerException e){
           System.out.println(e);
       }
    }

}
