/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse53.stm.view;

import cambodia.raven.DateChooser;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import lk.ijse.gdse53.stm.controller.AttendanceFormController;
import lk.ijse.gdse53.stm.model.ADetails;

/**
 *
 * @author Yashitha Nadiranga
 */
public class ViewAttendanceForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddStudentForm
     */
    public ViewAttendanceForm() {
        initComponents();
        loadUI();
        loadTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new cambodia.raven.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAllAttendance = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btndatesearch = new keeptoo.KButton();
        txtdatesearch = new javax.swing.JTextField();
        btndateserch1 = new keeptoo.KButton();

        dateChooser.setButton(btndatesearch);
        dateChooser.setTextRefernce(txtdatesearch);

        setBackground(new java.awt.Color(53, 63, 89));
        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setFrameIcon(null);

        jPanel1.setBackground(new java.awt.Color(53, 63, 89));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Attendance");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        kGradientPanel1.setBackground(new java.awt.Color(53, 63, 89));
        kGradientPanel1.setkBorderRadius(20);
        kGradientPanel1.setkEndColor(new java.awt.Color(11, 182, 83));
        kGradientPanel1.setkStartColor(new java.awt.Color(11, 182, 83));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 40, 870, 40));

        tblAllAttendance.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblAllAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RID", "Name", "Batch", "Course", "Subject", "Date"
            }
        ));
        tblAllAttendance.setGridColor(new java.awt.Color(204, 204, 204));
        tblAllAttendance.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tblAllAttendance.setRowHeight(25);
        tblAllAttendance.setSelectionBackground(new java.awt.Color(101, 52, 172));
        tblAllAttendance.setShowVerticalLines(false);
        tblAllAttendance.getTableHeader().setReorderingAllowed(false);
        tblAllAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAllAttendanceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAllAttendance);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 1050, 460));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, -1, 40));

        btndatesearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_age_30px.png"))); // NOI18N
        btndatesearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btndatesearch.setIconTextGap(15);
        btndatesearch.setkAllowGradient(false);
        btndatesearch.setkBackGroundColor(new java.awt.Color(53, 63, 89));
        btndatesearch.setkHoverColor(new java.awt.Color(53, 63, 89));
        btndatesearch.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btndatesearch.setkPressedColor(new java.awt.Color(53, 63, 89));
        btndatesearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatesearchActionPerformed(evt);
            }
        });
        jPanel1.add(btndatesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 140, 50, 40));

        txtdatesearch.setBackground(new java.awt.Color(53, 63, 89));
        txtdatesearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtdatesearch.setForeground(new java.awt.Color(255, 255, 255));
        txtdatesearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtdatesearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdatesearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtdatesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 180, 30));

        btndateserch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_search_20px.png"))); // NOI18N
        btndateserch1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btndateserch1.setIconTextGap(15);
        btndateserch1.setkAllowGradient(false);
        btndateserch1.setkBackGroundColor(new java.awt.Color(11, 182, 83));
        btndateserch1.setkHoverColor(new java.awt.Color(9, 135, 62));
        btndateserch1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btndateserch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndateserch1ActionPerformed(evt);
            }
        });
        jPanel1.add(btndateserch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 140, 50, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1115, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblAllAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAllAttendanceMouseClicked

    }//GEN-LAST:event_tblAllAttendanceMouseClicked

    private void txtdatesearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdatesearchKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatesearchKeyReleased

    private void btndateserch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndateserch1ActionPerformed
        dateSearch();
    }//GEN-LAST:event_btndateserch1ActionPerformed

    private void btndatesearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatesearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndatesearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btndatesearch;
    private keeptoo.KButton btndateserch1;
    private cambodia.raven.DateChooser dateChooser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTable tblAllAttendance;
    private javax.swing.JTextField txtdatesearch;
    // End of variables declaration//GEN-END:variables

    private void loadUI() {
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        tblAllAttendance.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        tblAllAttendance.getTableHeader().setOpaque(false);
        tblAllAttendance.getTableHeader().setBackground(new Color(32, 136, 203));
        tblAllAttendance.getTableHeader().setForeground(new Color(255,255,255));
        tblAllAttendance.getTableHeader().setBorder(new LineBorder(Color.white));
        tblAllAttendance.setRowHeight(30);
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());
    }

    private void loadTable() {
        try {
            List<ADetails> list = new AttendanceFormController().loadTableAll();
            DefaultTableModel model = (DefaultTableModel) tblAllAttendance.getModel();
            list.forEach((aDetails) -> {
                model.addRow(new Object[]{aDetails.getRid(), aDetails.getName(), aDetails.getBatch(), aDetails.getCourse(), aDetails.getSubject(), aDetails.getDate()});
            });
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewAttendanceForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void dateSearch() {
        try {
            String date = dateChooser.getSelectedDate(DateChooser.GET_YEAR) + "-"
                + dateChooser.getSelectedDate(DateChooser.GET_MONTH)
                + "-" + dateChooser.getSelectedDate(DateChooser.GET_DAY);
            List<ADetails> list = new AttendanceFormController().loadTableAllsearch(date);
            DefaultTableModel model = (DefaultTableModel) tblAllAttendance.getModel();
            model.setRowCount(0);
            list.forEach((aDetails) -> {
                model.addRow(new Object[]{aDetails.getRid(), aDetails.getName(), aDetails.getBatch(), aDetails.getCourse(), aDetails.getSubject(), aDetails.getDate()});
            });
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewAttendanceForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
