/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse53.stm.view;

import cambodia.raven.DateChooser;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import lk.ijse.gdse53.stm.controller.ViewRegistrationDetailsFormController;
import lk.ijse.gdse53.stm.model.SRDetail;

/**
 *
 * @author Yashitha Nadiranga
 */
public class ViewRegistrationDetailsForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddStudentForm
     */
    public static String ssid;
    
    public ViewRegistrationDetailsForm() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        //setBackground(new Color(0,0,0,0));
        tblregistrationview.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        tblregistrationview.getTableHeader().setOpaque(false);
        tblregistrationview.getTableHeader().setBackground(new Color(32, 136, 203));
        tblregistrationview.getTableHeader().setForeground(new Color(255,255,255));
        tblregistrationview.getTableHeader().setBorder(new LineBorder(Color.white));
        tblregistrationview.setRowHeight(30);
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        loadAllDetails();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new cambodia.raven.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblregistrationview = new javax.swing.JTable();
        btndatesearch = new keeptoo.KButton();
        jLabel2 = new javax.swing.JLabel();
        txtRidSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNameSearch = new javax.swing.JTextField();
        btnSerchsid = new keeptoo.KButton();
        btnNameSearch = new keeptoo.KButton();
        jLabel5 = new javax.swing.JLabel();
        txtdatesearch = new javax.swing.JTextField();
        btndateserch1 = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();

        dateChooser.setButton(btndatesearch);
        dateChooser.setTextRefernce(txtdatesearch);

        setBackground(new java.awt.Color(53, 63, 89));
        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setFrameIcon(null);

        jPanel1.setBackground(new java.awt.Color(53, 63, 89));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblregistrationview.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblregistrationview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SID", "RID", "Name", "Batch", "Date", "Reg Fee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblregistrationview.setFocusable(false);
        tblregistrationview.setGridColor(new java.awt.Color(204, 204, 204));
        tblregistrationview.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tblregistrationview.setRowHeight(25);
        tblregistrationview.setSelectionBackground(new java.awt.Color(101, 52, 172));
        tblregistrationview.setShowVerticalLines(false);
        tblregistrationview.getTableHeader().setReorderingAllowed(false);
        tblregistrationview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblregistrationviewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblregistrationview);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 1090, 460));
        jScrollPane1.getAccessibleContext().setAccessibleParent(this);

        btndatesearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_age_30px.png"))); // NOI18N
        btndatesearch.setDoubleBuffered(true);
        btndatesearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btndatesearch.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btndatesearch.setIconTextGap(15);
        btndatesearch.setkAllowGradient(false);
        btndatesearch.setkBackGroundColor(new java.awt.Color(53, 63, 89));
        btndatesearch.setkHoverColor(new java.awt.Color(53, 63, 89));
        btndatesearch.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btndatesearch.setkPressedColor(new java.awt.Color(53, 63, 89));
        btndatesearch.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btndatesearch.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btndatesearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatesearchActionPerformed(evt);
            }
        });
        jPanel1.add(btndatesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 140, 50, 40));

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("View Student Registration");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txtRidSearch.setBackground(new java.awt.Color(53, 63, 89));
        txtRidSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtRidSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtRidSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtRidSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRidSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtRidSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 140, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RID : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        txtNameSearch.setBackground(new java.awt.Color(53, 63, 89));
        txtNameSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNameSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtNameSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtNameSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtNameSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 170, 30));

        btnSerchsid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_search_20px.png"))); // NOI18N
        btnSerchsid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSerchsid.setIconTextGap(15);
        btnSerchsid.setkAllowGradient(false);
        btnSerchsid.setkBackGroundColor(new java.awt.Color(11, 182, 83));
        btnSerchsid.setkHoverColor(new java.awt.Color(9, 135, 62));
        btnSerchsid.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnSerchsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerchsidActionPerformed(evt);
            }
        });
        jPanel1.add(btnSerchsid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 50, 40));

        btnNameSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_search_20px.png"))); // NOI18N
        btnNameSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNameSearch.setIconTextGap(15);
        btnNameSearch.setkAllowGradient(false);
        btnNameSearch.setkBackGroundColor(new java.awt.Color(11, 182, 83));
        btnNameSearch.setkHoverColor(new java.awt.Color(9, 135, 62));
        btnNameSearch.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnNameSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNameSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnNameSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 50, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, -1, 40));

        txtdatesearch.setBackground(new java.awt.Color(53, 63, 89));
        txtdatesearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtdatesearch.setForeground(new java.awt.Color(255, 255, 255));
        txtdatesearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtdatesearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdatesearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtdatesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 210, 30));

        btndateserch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_search_20px.png"))); // NOI18N
        btndateserch1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btndateserch1.setIconTextGap(15);
        btndateserch1.setkAllowGradient(false);
        btndateserch1.setkBackGroundColor(new java.awt.Color(11, 182, 83));
        btndateserch1.setkHoverColor(new java.awt.Color(9, 135, 62));
        btndateserch1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btndateserch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndateserch1ActionPerformed(evt);
            }
        });
        jPanel1.add(btndateserch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 150, 50, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_refresh_30px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1114, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNameSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNameSearchActionPerformed
        
    }//GEN-LAST:event_btnNameSearchActionPerformed

    private void btnSerchsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerchsidActionPerformed
        
    }//GEN-LAST:event_btnSerchsidActionPerformed

    private void txtRidSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRidSearchKeyReleased
        ridSearch();
    }//GEN-LAST:event_txtRidSearchKeyReleased

    private void txtNameSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameSearchKeyReleased
        nameSearch();
    }//GEN-LAST:event_txtNameSearchKeyReleased

    private void tblregistrationviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblregistrationviewMouseClicked
        int r = tblregistrationview.getSelectedRow();
        ssid = tblregistrationview.getValueAt(r, 0).toString();
    }//GEN-LAST:event_tblregistrationviewMouseClicked

    private void txtdatesearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdatesearchKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatesearchKeyReleased

    private void btndatesearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatesearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndatesearchActionPerformed

    private void btndateserch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndateserch1ActionPerformed
        dateSearch();
    }//GEN-LAST:event_btndateserch1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        loadAllDetails();
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnNameSearch;
    private keeptoo.KButton btnSerchsid;
    private keeptoo.KButton btndatesearch;
    private keeptoo.KButton btndateserch1;
    private cambodia.raven.DateChooser dateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblregistrationview;
    private javax.swing.JTextField txtNameSearch;
    private javax.swing.JTextField txtRidSearch;
    private javax.swing.JTextField txtdatesearch;
    // End of variables declaration//GEN-END:variables

    private void loadAllDetails() {
        try {
            List<SRDetail> list = new ViewRegistrationDetailsFormController().getDetails();
            DefaultTableModel model = (DefaultTableModel) tblregistrationview.getModel();
            model.setRowCount(0);
            list.forEach((OBJ) -> {
                model.addRow(new Object[]{OBJ.getSid(), OBJ.getRid(), OBJ.getName(), OBJ.getBatch(),OBJ.getDate(),OBJ.getFee()
                        
                });
            });
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewRegistrationDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void ridSearch() {
        try {
            String rid = txtRidSearch.getText();
            List<SRDetail> list = new ViewRegistrationDetailsFormController().ridSearch(rid);
            DefaultTableModel model = (DefaultTableModel) tblregistrationview.getModel();      
            model.setRowCount(0);
            list.forEach((sRDetail) -> {
                model.addRow(new Object[]{sRDetail.getSid(),sRDetail.getRid(), sRDetail.getName(), sRDetail.getBatch(),sRDetail.getDate(),sRDetail.getFee() });
            });
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewRegistrationDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
        private void nameSearch() {
        try {
            String name = txtNameSearch.getText();
            List<SRDetail> list = new ViewRegistrationDetailsFormController().nameSearch(name);
            DefaultTableModel model = (DefaultTableModel) tblregistrationview.getModel();      
            model.setRowCount(0);
            list.forEach((sRDetail) -> {
                model.addRow(new Object[]{sRDetail.getSid(),sRDetail.getRid(), sRDetail.getName(), sRDetail.getBatch(),sRDetail.getDate(),sRDetail.getFee() });
            });
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewRegistrationDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void dateSearch() {
        try {
            String date=dateChooser.getSelectedDate(DateChooser.GET_YEAR)+"-"+dateChooser.getSelectedDate(DateChooser.GET_MONTH)+"-"+dateChooser.getSelectedDate(DateChooser.GET_DAY);
            List<SRDetail> list = new ViewRegistrationDetailsFormController().dateSearch(date);
            DefaultTableModel model = (DefaultTableModel) tblregistrationview.getModel();
            model.setRowCount(0);
            list.forEach((sRDetail) -> {
                model.addRow(new Object[]{sRDetail.getSid(),sRDetail.getRid(), sRDetail.getName(), sRDetail.getBatch(),sRDetail.getDate(),sRDetail.getFee() });
            });
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewRegistrationDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
