/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse53.stm.view;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import jssc.SerialPortException;
import lk.ijse.gdse53.stm.controller.RegisterStudentFormController;
import lk.ijse.gdse53.stm.controller.ViewStudentFormController;
import lk.ijse.gdse53.stm.model.Student;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Yashitha Nadiranga
 */
public class ViewStudentForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddStudentForm
     */
    public static String ssid;
    String privilege;
    public ViewStudentForm(String privilege) {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        //setBackground(new Color(0,0,0,0));
        tblstudentview.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        tblstudentview.getTableHeader().setOpaque(false);
        tblstudentview.getTableHeader().setBackground(new Color(32, 136, 203));
        tblstudentview.getTableHeader().setForeground(new Color(255, 255, 255));
        tblstudentview.getTableHeader().setBorder(new LineBorder(Color.white));
        tblstudentview.setRowHeight(30);
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        loadAllStudent();
        btnreg.setVisible(false);
        this.privilege = privilege;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblstudentview = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtSidSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNameSearch = new javax.swing.JTextField();
        btnSerchsid = new keeptoo.KButton();
        btnNameSearch = new keeptoo.KButton();
        btnmanage = new keeptoo.KButton();
        btnviewAllDetails2 = new keeptoo.KButton();
        lblreg = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnreg = new keeptoo.KButton();

        setBackground(new java.awt.Color(53, 63, 89));
        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setFrameIcon(null);

        jPanel1.setBackground(new java.awt.Color(53, 63, 89));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblstudentview.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblstudentview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SID", "Name", "Contact", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblstudentview.setFocusable(false);
        tblstudentview.setGridColor(new java.awt.Color(204, 204, 204));
        tblstudentview.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tblstudentview.setRowHeight(25);
        tblstudentview.setSelectionBackground(new java.awt.Color(101, 52, 172));
        tblstudentview.setShowVerticalLines(false);
        tblstudentview.getTableHeader().setReorderingAllowed(false);
        tblstudentview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblstudentviewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblstudentview);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 1090, 460));
        jScrollPane1.getAccessibleContext().setAccessibleParent(this);

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("View Student");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txtSidSearch.setBackground(new java.awt.Color(53, 63, 89));
        txtSidSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSidSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtSidSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtSidSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSidSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtSidSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SID : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        txtNameSearch.setBackground(new java.awt.Color(53, 63, 89));
        txtNameSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNameSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtNameSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtNameSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtNameSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 220, 30));

        btnSerchsid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_search_20px.png"))); // NOI18N
        btnSerchsid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSerchsid.setIconTextGap(15);
        btnSerchsid.setkAllowGradient(false);
        btnSerchsid.setkBackGroundColor(new java.awt.Color(11, 182, 83));
        btnSerchsid.setkHoverColor(new java.awt.Color(9, 135, 62));
        btnSerchsid.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnSerchsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerchsidActionPerformed(evt);
            }
        });
        jPanel1.add(btnSerchsid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 50, 40));

        btnNameSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_search_20px.png"))); // NOI18N
        btnNameSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNameSearch.setIconTextGap(15);
        btnNameSearch.setkAllowGradient(false);
        btnNameSearch.setkBackGroundColor(new java.awt.Color(11, 182, 83));
        btnNameSearch.setkHoverColor(new java.awt.Color(9, 135, 62));
        btnNameSearch.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnNameSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNameSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnNameSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 50, 40));

        btnmanage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse53/stm/view/images/icons8_manager_20px.png"))); // NOI18N
        btnmanage.setText("Manage Student");
        btnmanage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnmanage.setIconTextGap(15);
        btnmanage.setkAllowGradient(false);
        btnmanage.setkBackGroundColor(new java.awt.Color(11, 182, 83));
        btnmanage.setkHoverColor(new java.awt.Color(9, 135, 62));
        btnmanage.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnmanage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanageActionPerformed(evt);
            }
        });
        jPanel1.add(btnmanage, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, 250, 40));

        btnviewAllDetails2.setText("View Registration Details");
        btnviewAllDetails2.setAlignmentX(0.5F);
        btnviewAllDetails2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnviewAllDetails2.setIconTextGap(0);
        btnviewAllDetails2.setkAllowGradient(false);
        btnviewAllDetails2.setkBackGroundColor(new java.awt.Color(11, 182, 83));
        btnviewAllDetails2.setkHoverColor(new java.awt.Color(9, 135, 62));
        btnviewAllDetails2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnviewAllDetails2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewAllDetails2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnviewAllDetails2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 700, 390, 50));

        lblreg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblreg.setForeground(new java.awt.Color(255, 255, 255));
        lblreg.setText("Not Selected");
        jPanel1.add(lblreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 720, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registration : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 720, -1, -1));

        btnreg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnreg.setkAllowGradient(false);
        btnreg.setkBackGroundColor(new java.awt.Color(255, 0, 51));
        btnreg.setkHoverColor(new java.awt.Color(0, 204, 102));
        btnreg.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnreg.setkPressedColor(new java.awt.Color(0, 255, 51));
        btnreg.setLabel("Register Student");
        btnreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregActionPerformed(evt);
            }
        });
        jPanel1.add(btnreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 710, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1114, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNameSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNameSearchActionPerformed
        serchName();
    }//GEN-LAST:event_btnNameSearchActionPerformed

    private void btnSerchsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerchsidActionPerformed
        searchSid();
    }//GEN-LAST:event_btnSerchsidActionPerformed

    private void txtSidSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSidSearchKeyReleased
        searchSid();
    }//GEN-LAST:event_txtSidSearchKeyReleased

    private void txtNameSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameSearchKeyReleased
        serchName();
    }//GEN-LAST:event_txtNameSearchKeyReleased

    private void btnmanageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanageActionPerformed
        jPanel1.setLayout(new FlowLayout());
        jPanel1.removeAll();
        jPanel1.repaint();
        jPanel1.add(new ManageStudentForm(privilege)).setVisible(true);
    }//GEN-LAST:event_btnmanageActionPerformed

    private void btnviewAllDetails2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewAllDetails2ActionPerformed
        jPanel1.setLayout(new FlowLayout());
        jPanel1.removeAll();
        jPanel1.repaint();
        jPanel1.add(new ViewRegistrationDetailsForm()).setVisible(true);
    }//GEN-LAST:event_btnviewAllDetails2ActionPerformed

    private void tblstudentviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblstudentviewMouseClicked
        int r = tblstudentview.getSelectedRow();
        ssid = tblstudentview.getValueAt(r, 0).toString();
        isContainregistration(ssid);
        
    }//GEN-LAST:event_tblstudentviewMouseClicked

    private void btnregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregActionPerformed
        jPanel1.setLayout(new FlowLayout());
        jPanel1.removeAll();
        jPanel1.repaint();
        try {
            jPanel1.add(new RegisterStudentForm(ssid,privilege)).setVisible(true);
        } catch (SerialPortException ex) {
            Logger.getLogger(ViewStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnregActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnNameSearch;
    private keeptoo.KButton btnSerchsid;
    private keeptoo.KButton btnmanage;
    private keeptoo.KButton btnreg;
    private keeptoo.KButton btnviewAllDetails2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblreg;
    private javax.swing.JTable tblstudentview;
    private javax.swing.JTextField txtNameSearch;
    private javax.swing.JTextField txtSidSearch;
    // End of variables declaration//GEN-END:variables

    private void loadAllStudent() {
        try {
            List <Student> list = new ViewStudentFormController().getAllStudent();
            DefaultTableModel model = (DefaultTableModel) tblstudentview.getModel();
            list.forEach((OBJ) -> {
                model.addRow(new Object[]{OBJ.getSid(), OBJ.getName(), OBJ.getTel1(), OBJ.getAddress()
                        
                });
                
            });
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void searchSid() {
        String sidserch = txtSidSearch.getText();
        try {
            ResultSet rs = (ResultSet) new ViewStudentFormController().getSearchSidStudent(sidserch);
            tblstudentview.setModel(DbUtils.resultSetToTableModel(rs));
           
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ViewStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void serchName() {
       String namesearch = txtNameSearch.getText();
        try {
            ResultSet rs = (ResultSet) new ViewStudentFormController().getSearchNameStudent(namesearch);
            tblstudentview.setModel(DbUtils.resultSetToTableModel(rs));
           
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ViewStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void isContainregistration(String r) {
        try {
            String contain = new RegisterStudentFormController().isContain(r);
            if(contain.equals(r)){
                lblreg.setForeground(new Color(11, 182, 83));
                lblreg.setText("Success");
                btnreg.setVisible(false);
            }else{
                lblreg.setForeground(new Color(245, 32, 62));
                lblreg.setText("No Registration Found");
                btnreg.setVisible(true);
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
